# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.05.010050'

RELEASE_GIT_HEAD = 'bf458510289d969b096856f328456f1ac3618564'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'tunaflsh/yt-dlp'

ORIGIN = 'tunaflsh/yt-dlp'

_pkg_version = '2025.12.05.010050'
